import { StyleSheet } from "react-native";

const GREEN = "#1DB954";

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#000000" },
  container: { flex: 1, backgroundColor: "#000000" },
  header: {
    backgroundColor: "#121212",
    borderBottomWidth: 1,
    borderBottomColor: "#262626",
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 18,
  },
  backRow: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    marginBottom: 16,
  },
  backText: {
    color: GREEN,
    fontSize: 15,
    fontWeight: "600",
    marginLeft: 8,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 120,
  },
  listHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  listTitle: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 4,
  },
  listSubtitle: {
    color: "#9CA3AF",
    fontSize: 13,
  },
  clockWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(29,185,84,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  searchWrap: {
    position: "relative",
    justifyContent: "center",
  },
  searchIcon: {
    position: "absolute",
    left: 14,
    zIndex: 1,
  },
  searchInput: {
    backgroundColor: "#000000",
    borderWidth: 1,
    borderColor: "#374151",
    borderRadius: 14,
    color: "#FFFFFF",
    paddingLeft: 42,
    paddingRight: 14,
    paddingVertical: 13,
    fontSize: 14,
  },
  historyCard: {
    backgroundColor: "#121212",
    borderWidth: 1,
    borderColor: "#1F2937",
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
  },
  historyCardTop: {
    flexDirection: "row",
    alignItems: "center",
  },
  historyCardBody: {
    flex: 1,
    paddingRight: 12,
  },
  historyCardTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 4,
  },
  historyCardMeta: {
    color: "#9CA3AF",
    fontSize: 13,
    marginBottom: 12,
  },
  historyStatsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  historyStatItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 14,
    marginBottom: 4,
  },
  historyStatText: {
    color: "#9CA3AF",
    fontSize: 12,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  dotSafe: { backgroundColor: "#22C55E" },
  dotWarn: { backgroundColor: "#EAB308" },
  dotUnsafe: { backgroundColor: "#EF4444" },
  emptyWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 70,
  },
  emptyIconWrap: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: "#111827",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  emptyTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 8,
  },
  emptyText: {
    color: "#9CA3AF",
    textAlign: "center",
    fontSize: 13,
    lineHeight: 19,
    maxWidth: 240,
    marginBottom: 18,
  },
  emptyBtn: {
    backgroundColor: GREEN,
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  emptyBtnText: {
    color: "#03150A",
    fontWeight: "800",
    fontSize: 14,
  },
  detailHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  detailHeaderBody: {
    flex: 1,
    paddingRight: 12,
  },
  resultsTitle: {
    color: "#FFFFFF",
    fontSize: 30,
    fontWeight: "800",
    marginBottom: 6,
  },
  resultsSubtitle: {
    color: "#9CA3AF",
    fontSize: 14,
    lineHeight: 20,
  },
  shieldBox: {
    width: 60,
    height: 60,
    borderRadius: 18,
    backgroundColor: GREEN,
    alignItems: "center",
    justifyContent: "center",
  },
  heroCard: {
    backgroundColor: "#121212",
    borderWidth: 1,
    borderColor: "#2A2A2A",
    borderRadius: 24,
    padding: 18,
    marginBottom: 18,
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  heroContent: {
    flex: 1,
    paddingRight: 14,
  },
  heroEyebrow: {
    color: "#9CA3AF",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  heroHeadline: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "800",
    marginBottom: 8,
  },
  heroSubtext: {
    color: "#A3A3A3",
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 10,
  },
  savedScanMeta: {
    color: "#9CA3AF",
    fontSize: 13,
    marginBottom: 4,
  },
  savedScanLocation: {
    color: "#6B7280",
    fontSize: 12,
  },
  scoreRing: {
    width: 82,
    height: 82,
    borderRadius: 41,
    borderWidth: 4,
    borderColor: GREEN,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(29,185,84,0.08)",
  },
  scoreValue: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
  },
  scoreLabel: {
    color: "#9CA3AF",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 2,
  },
  insightRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  insightPill: {
    flex: 1,
    backgroundColor: "#0F0F0F",
    borderWidth: 1,
    borderColor: "#242424",
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 10,
    marginRight: 10,
  },
  insightPillLast: {
    marginRight: 0,
  },
  insightValueSafe: {
    color: "#22C55E",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 4,
    textAlign: "center",
  },
  insightValueWarning: {
    color: "#FACC15",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 4,
    textAlign: "center",
  },
  insightValueUnsafe: {
    color: "#F87171",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 4,
    textAlign: "center",
  },
  insightText: {
    color: "#9CA3AF",
    fontSize: 12,
    textAlign: "center",
    lineHeight: 16,
  },
  safetyCard: {
    backgroundColor: "rgba(0,59,28,0.45)",
    borderWidth: 1.4,
    borderColor: "rgba(29,185,84,0.32)",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 18,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  safetyIconCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: GREEN,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  safetyTextWrap: {
    flex: 1,
  },
  safetyTitle: {
    color: GREEN,
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 4,
  },
  safetyDescription: {
    color: "#D1D5DB",
    fontSize: 13,
    lineHeight: 18,
  },
  sectionGroup: {
    marginTop: 26,
  },
  sectionGroupHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  sectionGroupTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
  },
  sectionGroupCount: {
    color: "#9CA3AF",
    fontSize: 13,
    fontWeight: "600",
  },
  dishCard: {
    borderWidth: 1.4,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 14,
    marginBottom: 12,
    backgroundColor: "#101010",
    overflow: "hidden",
  },
  dishCardSafe: {
    borderColor: "#00E46C",
    backgroundColor: "rgba(0,48,22,0.45)",
  },
  dishCardWarning: {
    borderColor: "#EAB308",
    backgroundColor: "rgba(46,32,0,0.42)",
  },
  dishCardUnsafe: {
    borderColor: "#EF4444",
    backgroundColor: "rgba(49,7,11,0.42)",
  },
  dishTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  dishTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
    marginLeft: 8,
    flex: 1,
  },
  dishStatusBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    marginBottom: 12,
  },
  dishStatusBadgeSafe: {
    backgroundColor: "rgba(34,197,94,0.16)",
  },
  dishStatusBadgeWarning: {
    backgroundColor: "rgba(234,179,8,0.16)",
  },
  dishStatusBadgeUnsafe: {
    backgroundColor: "rgba(239,68,68,0.16)",
  },
  dishStatusBadgeTextSafe: {
    color: "#22C55E",
    fontSize: 12,
    fontWeight: "800",
  },
  dishStatusBadgeTextWarning: {
    color: "#FACC15",
    fontSize: 12,
    fontWeight: "800",
  },
  dishStatusBadgeTextUnsafe: {
    color: "#F87171",
    fontSize: 12,
    fontWeight: "800",
  },
  dishDescription: {
    color: "#D1D5DB",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  recommendationBox: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
  },
  recommendationText: {
    color: "#E5E7EB",
    fontSize: 13,
    lineHeight: 19,
  },
  categoryChip: {
    alignSelf: "flex-start",
    backgroundColor: "#25324A",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 14,
  },
  categoryChipText: {
    color: "#B5C0D1",
    fontSize: 11,
    fontWeight: "600",
  },
  blockTitle: {
    color: "#D1D5DB",
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 10,
  },
  chipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 16,
  },
  allergenChip: {
    backgroundColor: "rgba(239,68,68,0.18)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 8,
    marginBottom: 8,
  },
  allergenChipText: {
    color: "#F87171",
    fontSize: 11,
    fontWeight: "700",
  },
  warningChip: {
    backgroundColor: "rgba(234,179,8,0.18)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 8,
    marginBottom: 8,
  },
  warningChipText: {
    color: "#FACC15",
    fontSize: 11,
    fontWeight: "700",
  },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#121212",
    borderTopWidth: 1,
    borderTopColor: "#1F2937",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 10,
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 64,
  },
  navLabel: {
    color: "#9CA3AF",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 5,
  },
  navCenterWrap: {
    marginTop: -26,
  },
  navCenterBtn: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: GREEN,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "#121212",
  },
});

export default styles;
