import { StyleSheet } from "react-native";

const GREEN = "#1DB954";

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#000000" },
  container: { flex: 1, backgroundColor: "#000000" },
  header: {
    backgroundColor: "#121212",
    borderBottomWidth: 1,
    borderBottomColor: "#262626",
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 18,
  },
  backRow: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    marginBottom: 16,
  },
  backText: {
    color: GREEN,
    fontSize: 15,
    fontWeight: "600",
    marginLeft: 8,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 18,
  },
  listHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  listHeaderTextWrap: {
    flex: 1,
    paddingRight: 14,
  },
  listTitle: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 4,
  },
  listSubtitle: {
    color: "#9CA3AF",
    fontSize: 13,
    lineHeight: 18,
  },
  summaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  summaryCard: {
    width: "48%",
    backgroundColor: "#121212",
    borderWidth: 1,
    borderColor: "#222938",
    borderRadius: 22,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  summaryLabel: {
    color: "#9CA3AF",
    fontSize: 12,
    marginBottom: 8,
  },
  summaryValue: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "800",
  },
  summaryValueSafe: {
    color: "#22C55E",
  },
  summaryValueWarning: {
    color: "#FACC15",
  },
  summaryValueUnsafe: {
    color: "#F87171",
  },
  headerOrb: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#123524",
    borderWidth: 1,
    borderColor: "rgba(29,185,84,0.28)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#1DB954",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  searchWrap: {
    position: "relative",
    justifyContent: "center",
  },
  searchIcon: {
    position: "absolute",
    left: 14,
    zIndex: 1,
  },
  searchInput: {
    backgroundColor: "#060606",
    borderWidth: 1,
    borderColor: "#2A3142",
    borderRadius: 18,
    color: "#FFFFFF",
    paddingLeft: 42,
    paddingRight: 14,
    paddingVertical: 14,
    fontSize: 14,
  },
  historyCard: {
    backgroundColor: "#121212",
    borderWidth: 1,
    borderColor: "#222938",
    borderRadius: 26,
    padding: 18,
    marginBottom: 14,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  historyAccentLine: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: "rgba(29,185,84,0.75)",
  },
  historyCardTop: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  historyCardBody: {
    flex: 1,
  },
  historyIntroRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  historyIntroBody: {
    flex: 1,
  },
  scanOrb: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
    borderWidth: 1,
  },
  scanOrbSafe: {
    backgroundColor: "rgba(34,197,94,0.18)",
    borderColor: "rgba(34,197,94,0.32)",
  },
  scanOrbRisky: {
    backgroundColor: "rgba(234,179,8,0.18)",
    borderColor: "rgba(234,179,8,0.32)",
  },
  scanOrbUnsafe: {
    backgroundColor: "rgba(239,68,68,0.18)",
    borderColor: "rgba(239,68,68,0.32)",
  },
  scanOrbNeutral: {
    backgroundColor: "rgba(148,163,184,0.18)",
    borderColor: "rgba(148,163,184,0.32)",
  },
  historyCardTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 8,
  },
  historyCardMeta: {
    color: "#9CA3AF",
    fontSize: 12,
    marginBottom: 0,
  },
  inlineMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    flexWrap: "wrap",
    gap: 8,
  },
  historyNarrative: {
    color: "#B6BCC8",
    fontSize: 14,
    lineHeight: 21,
  },
  historyBottomRow: {
    marginBottom: 10,
  },
  historyStatsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 12,
  },
  historyStatPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0D1118",
    borderWidth: 1,
    borderColor: "#1E2633",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginRight: 8,
    marginBottom: 8,
  },
  historyStatText: {
    color: "#D1D5DB",
    fontSize: 12,
    fontWeight: "600",
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  historyActionWrap: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#0D1118",
    borderWidth: 1,
    borderColor: "#1E2633",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  historyActionText: {
    color: "#D1D5DB",
    fontSize: 12,
    fontWeight: "700",
    marginRight: 8,
  },
  dotSafe: { backgroundColor: "#22C55E" },
  dotWarn: { backgroundColor: "#EAB308" },
  dotUnsafe: { backgroundColor: "#EF4444" },
  emptyWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 70,
  },
  emptyIconWrap: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: "#111827",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  emptyTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 8,
  },
  emptyText: {
    color: "#9CA3AF",
    textAlign: "center",
    fontSize: 13,
    lineHeight: 19,
    maxWidth: 280,
    marginBottom: 18,
  },
  emptyBtn: {
    backgroundColor: GREEN,
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  emptyBtnText: {
    color: "#03150A",
    fontWeight: "800",
    fontSize: 14,
  },
  statusCard: {
    backgroundColor: "#121212",
    borderWidth: 1,
    borderColor: "#1F2937",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  statusText: {
    color: "#D1D5DB",
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
    marginTop: 10,
  },
  errorText: {
    color: "#FCA5A5",
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  paginationWrap: {
    marginTop: 8,
    marginBottom: 12,
  },
  paginationRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  pageBtn: {
    flex: 1,
    backgroundColor: "#121212",
    borderWidth: 1,
    borderColor: "#374151",
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    marginHorizontal: 4,
  },
  pageBtnDisabled: {
    opacity: 0.45,
  },
  pageBtnText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },
  detailHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  detailHeaderBody: {
    flex: 1,
    paddingRight: 12,
  },
  resultsTitle: {
    color: "#FFFFFF",
    fontSize: 30,
    fontWeight: "800",
    marginBottom: 6,
  },
  resultsSubtitle: {
    color: "#9CA3AF",
    fontSize: 14,
    lineHeight: 20,
  },
  shieldBox: {
    width: 60,
    height: 60,
    borderRadius: 18,
    backgroundColor: GREEN,
    alignItems: "center",
    justifyContent: "center",
  },
  heroCard: {
    backgroundColor: "#121212",
    borderWidth: 1,
    borderColor: "#222938",
    borderRadius: 28,
    padding: 20,
    marginBottom: 18,
  },
  detailHeroHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 18,
  },
  detailHeroOrb: {
    width: 58,
    height: 58,
    borderRadius: 20,
    backgroundColor: "#123524",
    borderWidth: 1,
    borderColor: "rgba(29,185,84,0.28)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  detailHeroIntro: {
    flex: 1,
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  heroContent: {
    flex: 1,
    paddingRight: 14,
  },
  heroEyebrow: {
    color: "#9CA3AF",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  heroHeadline: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "800",
    marginBottom: 8,
  },
  heroSubtext: {
    color: "#A3A3A3",
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 10,
  },
  savedScanMeta: {
    color: "#9CA3AF",
    fontSize: 13,
    marginBottom: 4,
  },
  savedScanLocation: {
    color: "#6B7280",
    fontSize: 12,
  },
  detailMetaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  detailMetaCard: {
    width: "48%",
    backgroundColor: "#0B0D12",
    borderWidth: 1,
    borderColor: "#1D2430",
    borderRadius: 18,
    padding: 14,
    marginBottom: 10,
  },
  detailMetaLabel: {
    color: "#7F8794",
    fontSize: 12,
    marginBottom: 7,
  },
  detailMetaValue: {
    color: "#F3F4F6",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  scoreRing: {
    width: 82,
    height: 82,
    borderRadius: 41,
    borderWidth: 4,
    borderColor: GREEN,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(29,185,84,0.08)",
  },
  scoreValue: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
  },
  scoreLabel: {
    color: "#9CA3AF",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 2,
  },
  insightRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  insightPill: {
    flex: 1,
    backgroundColor: "#0F0F0F",
    borderWidth: 1,
    borderColor: "#242424",
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 10,
    marginRight: 10,
  },
  insightPillLast: {
    marginRight: 0,
  },
  insightValueSafe: {
    color: "#22C55E",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 4,
    textAlign: "center",
  },
  insightValueWarning: {
    color: "#FACC15",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 4,
    textAlign: "center",
  },
  insightValueUnsafe: {
    color: "#F87171",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 4,
    textAlign: "center",
  },
  insightText: {
    color: "#9CA3AF",
    fontSize: 12,
    textAlign: "center",
    lineHeight: 16,
  },
  sectionGroup: {
    marginTop: 10,
  },
  sectionGroupHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  sectionGroupTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
  },
  sectionGroupCount: {
    color: "#9CA3AF",
    fontSize: 13,
    fontWeight: "600",
  },
  dishCard: {
    borderWidth: 1.4,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    marginBottom: 14,
    backgroundColor: "#101217",
    overflow: "hidden",
  },
  dishCardSafe: {
    borderColor: "rgba(34,197,94,0.4)",
    backgroundColor: "rgba(7,31,18,0.92)",
  },
  dishCardWarning: {
    borderColor: "rgba(234,179,8,0.4)",
    backgroundColor: "rgba(36,28,6,0.92)",
  },
  dishCardUnsafe: {
    borderColor: "rgba(239,68,68,0.4)",
    backgroundColor: "rgba(41,10,14,0.92)",
  },
  dishCardNeutral: {
    borderColor: "rgba(148,163,184,0.32)",
    backgroundColor: "#101217",
  },
  dishCardTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  dishTitleCluster: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    paddingRight: 10,
  },
  dishIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  dishTitleTextWrap: {
    flex: 1,
  },
  dishEyebrow: {
    color: "#8E97A5",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  dishTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  dishTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
    flex: 1,
  },
  detailPill: {
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  dishStatusBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    marginBottom: 12,
  },
  dishStatusBadgeSafe: {
    backgroundColor: "rgba(34,197,94,0.16)",
  },
  dishStatusBadgeWarning: {
    backgroundColor: "rgba(234,179,8,0.16)",
  },
  dishStatusBadgeUnsafe: {
    backgroundColor: "rgba(239,68,68,0.16)",
  },
  dishStatusBadgeNeutral: {
    backgroundColor: "rgba(148,163,184,0.16)",
  },
  dishStatusBadgeTextSafe: {
    color: "#22C55E",
    fontSize: 12,
    fontWeight: "800",
  },
  dishStatusBadgeTextWarning: {
    color: "#FACC15",
    fontSize: 12,
    fontWeight: "800",
  },
  dishStatusBadgeTextUnsafe: {
    color: "#F87171",
    fontSize: 12,
    fontWeight: "800",
  },
  dishStatusBadgeTextNeutral: {
    color: "#CBD5E1",
    fontSize: 12,
    fontWeight: "800",
  },
  dishDescription: {
    color: "#D1D5DB",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  detailNarrativeCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
  },
  detailNarrativeLabel: {
    color: "#9CA3AF",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  detailNarrativeText: {
    color: "#F3F4F6",
    fontSize: 13,
    lineHeight: 20,
  },
  detailSection: {
    marginBottom: 4,
  },
  recommendationBox: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
  },
  recommendationText: {
    color: "#E5E7EB",
    fontSize: 13,
    lineHeight: 19,
  },
  categoryChip: {
    alignSelf: "flex-start",
    backgroundColor: "#25324A",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 14,
  },
  categoryChipText: {
    color: "#B5C0D1",
    fontSize: 11,
    fontWeight: "600",
  },
  ingredientChip: {
    alignSelf: "flex-start",
    backgroundColor: "#101A28",
    borderWidth: 1,
    borderColor: "#233047",
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
    marginRight: 8,
    marginBottom: 8,
  },
  ingredientChipText: {
    color: "#D5DFEF",
    fontSize: 11,
    fontWeight: "700",
  },
  blockTitle: {
    color: "#D1D5DB",
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 10,
  },
  chipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 4,
  },
  allergenChip: {
    backgroundColor: "rgba(239,68,68,0.18)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 8,
    marginBottom: 8,
  },
  allergenChipText: {
    color: "#F87171",
    fontSize: 11,
    fontWeight: "700",
  },
  warningChip: {
    backgroundColor: "rgba(234,179,8,0.18)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 8,
    marginBottom: 8,
  },
  warningChipText: {
    color: "#FACC15",
    fontSize: 11,
    fontWeight: "700",
  },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#121212",
    borderTopWidth: 1,
    borderTopColor: "#1F2937",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingTop: 8,
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 64,
  },
  navLabel: {
    color: "#9CA3AF",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 5,
  },
  navCenterWrap: {
    marginTop: -26,
  },
  navCenterBtn: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: GREEN,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "#121212",
  },
});

export default styles;
