import { StyleSheet } from "react-native";

const GREEN = "#1DB954";
const BG = "#000000";
const CARD = "#121212";
const BORDER = "#2A2A2A";
const MUTED = "#9CA3AF";

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: BG },
  container: { flex: 1, backgroundColor: BG },

  scrollView: {
    flex: 1,
    backgroundColor: BG,
  },
  scroll: {
    flexGrow: 1,
    minHeight: "100%",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 26,
  },
  scrollWithTopAlert: {
    paddingTop: 74,
  },

  backRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  backArrow: { color: GREEN, fontSize: 26, marginTop: -2 },
  backText: { color: GREEN, fontSize: 14, fontWeight: "700" },

  logoWrap: { alignItems: "center", marginTop: 6, marginBottom: 8 },
  logo: { width: 72, height: 72 },

  progressWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 6,
    marginBottom: 14,
  },
  progressItem: { alignItems: "center" },
  circle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  circleOn: { backgroundColor: GREEN },
  circleOff: { backgroundColor: "#2F2F2F" },
  circleTxtOn: { color: "#000", fontWeight: "900" },
  circleTxtOff: { color: "#9AA0A6", fontWeight: "900" },
  progressLine: {
    width: 70,
    height: 4,
    backgroundColor: "#2F2F2F",
    marginHorizontal: 12,
  },
  progressLineOn: { backgroundColor: GREEN },
  progressLabelOn: {
    color: "#fff",
    fontSize: 12,
    marginTop: 6,
    fontWeight: "700",
  },
  progressLabelOff: {
    color: "#9AA0A6",
    fontSize: 12,
    marginTop: 6,
    fontWeight: "700",
  },

  h1: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 6,
  },
  sub: { color: MUTED, textAlign: "center", marginTop: 6, marginBottom: 12 },
  sub2: { color: MUTED, textAlign: "center", marginTop: 6, marginBottom: 18 },

  label: {
    color: "#D1D5DB",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 12,
    marginBottom: 6,
  },
  input: {
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#fff",
  },
  inputError: {
    borderColor: "#F87171",
    backgroundColor: "rgba(248,113,113,0.08)",
  },
  errorText: {
    color: "#FCA5A5",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 6,
  },
  topValidationAlert: {
    position: "absolute",
    top: 12,
    left: 16,
    right: 16,
    zIndex: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(248,113,113,0.45)",
    backgroundColor: "rgba(40,12,12,0.96)",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  topValidationAlertText: {
    flex: 1,
    color: "#FECACA",
    fontSize: 12,
    fontWeight: "700",
  },
  phoneWrap: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 10,
  },
  countryBtn: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    borderRightWidth: 1,
    borderRightColor: BORDER,
  },
  countryFlag: { fontSize: 18 },
  countryCode: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" },
  phoneInput: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#fff",
  },
  passwordWrap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 10,
  },
  passwordInput: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#fff",
  },
  eyeBtn: {
    minWidth: 44,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  passwordStrength: {
    marginTop: 8,
    gap: 7,
  },
  passwordStrengthHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  passwordStrengthLabel: {
    color: MUTED,
    fontSize: 12,
    fontWeight: "800",
  },
  passwordStrengthValue: {
    fontSize: 12,
    fontWeight: "900",
  },
  passwordStrengthTrack: {
    flexDirection: "row",
    gap: 5,
  },
  passwordStrengthSegment: {
    flex: 1,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#1F2937",
    borderWidth: 1,
    borderColor: "#374151",
  },
  passwordRules: {
    marginTop: 8,
    gap: 6,
  },
  passwordRule: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  passwordRuleText: {
    color: "#9CA3AF",
    fontSize: 12,
  },
  passwordRuleTextMet: {
    color: "#D1FAE5",
  },

  inputBtn: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: "space-between",
    gap: 10,
  },
  inputBtnFocused: { borderColor: GREEN },
  inputBtnText: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 14,
  },
  dateDoneBtn: {
    backgroundColor: GREEN,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  dateDoneText: {
    color: "#03150A",
    fontSize: 12,
    fontWeight: "900",
  },

  row2: { flexDirection: "row", gap: 12 },
  rowHalf: { flex: 1 },

  genderRow: { flexDirection: "row", gap: 12, marginTop: 6 },
  genderCard: {
    flex: 1,
    borderWidth: 2,
    borderRadius: 12,
    paddingVertical: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: CARD,
  },
  genderCardOff: { borderColor: BORDER },
  genderCardError: { borderColor: "#F87171" },
  genderCardOn: {
    borderColor: GREEN,
    backgroundColor: "rgba(29,185,84,0.12)",
  },
  genderIcon: { color: "#9AA0A6", fontSize: 26, marginBottom: 6 },
  genderIconOn: { color: GREEN },
  genderText: { color: "#9AA0A6", fontWeight: "800" },
  genderTextOn: { color: GREEN },

  mainBtn: {
    backgroundColor: GREEN,
    borderRadius: 10,
    marginTop: 18,
    paddingVertical: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  mainBtnDisabled: { opacity: 0.7 },
  mainBtnTxt: { color: "#000", fontWeight: "900", fontSize: 14 },

  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.72)",
    justifyContent: "flex-end",
    padding: 20,
  },
  countrySheet: {
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 14,
    padding: 14,
    maxHeight: "72%",
  },
  countrySheetTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 8,
  },
  countryList: {
    maxHeight: "92%",
  },
  countryOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 10,
  },
  countryOptionActive: {
    backgroundColor: "rgba(29,185,84,0.12)",
  },
  countryOptionFlag: {
    fontSize: 22,
    width: 30,
    textAlign: "center",
  },
  countryOptionTextWrap: { flex: 1 },
  countryOptionName: { color: "#FFFFFF", fontWeight: "800" },
  countryOptionCode: { color: MUTED, marginTop: 2, fontSize: 12 },

  bottomText: {
    color: MUTED,
    textAlign: "center",
    marginTop: 14,
    fontSize: 12,
  },
  bottomTextGreen: { color: GREEN, fontWeight: "900" },

  q: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
    marginTop: 14,
    marginBottom: 10,
  },
  qSpaced: { marginTop: 18 },

  yesNoRow: { flexDirection: "row", gap: 12 },
  yesNoBtn: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  yesNoBtnOn: { backgroundColor: GREEN, borderColor: GREEN },
  yesNoBtnOff: { backgroundColor: "#FFFFFF", borderColor: "#FFFFFF" },
  yesNoTxt: { fontWeight: "900" },
  yesNoTxtOn: { color: "#000" },

  box: {
    marginTop: 12,
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 12,
    padding: 14,
    maxHeight: 290,
    overflow: "hidden",
  },
  allergyDropdown: {
    marginTop: 10,
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 12,
    overflow: "hidden",
  },
  allergyDropdownClosed: {
    borderRadius: 10,
  },
  allergyDropdownHeader: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: BORDER,
  },
  allergyDropdownTitleRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  allergyDropdownTitle: {
    flexShrink: 1,
    color: "#E5E7EB",
    fontSize: 14,
    fontWeight: "900",
  },
  selectedCountPill: {
    backgroundColor: "rgba(29,185,84,0.2)",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  selectedCountText: {
    color: "#7DE2A2",
    fontSize: 12,
    fontWeight: "900",
  },
  allergyHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  allergyClearBtn: {
    minHeight: 30,
    borderWidth: 1,
    borderColor: "#374151",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  allergyClearText: {
    color: "#9CA3AF",
    fontSize: 12,
    fontWeight: "800",
  },
  selectedAllergyChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 10,
  },
  selectedAllergyChip: {
    minHeight: 30,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: "rgba(29,185,84,0.35)",
    backgroundColor: "rgba(29,185,84,0.13)",
    borderRadius: 999,
    paddingHorizontal: 11,
  },
  selectedAllergyChipText: {
    color: "#7DE2A2",
    fontSize: 12,
    fontWeight: "900",
  },
  allergySearchWrap: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginHorizontal: 14,
    marginTop: 10,
    marginBottom: 10,
    backgroundColor: "#1A1A1A",
    borderWidth: 1,
    borderColor: "#2A2A2A",
    borderRadius: 10,
    paddingHorizontal: 12,
  },
  allergySearchInput: {
    flex: 1,
    color: "#FFFFFF",
    paddingVertical: 9,
  },
  dropdownSummary: {
    marginTop: 10,
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  dropdownSummaryText: {
    flex: 1,
    color: "#E5E7EB",
    fontSize: 13,
    fontWeight: "700",
  },
  boxHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  },
  boxTitle: { color: "#D1D5DB", fontWeight: "800" },
  dropdownActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  clearAllBtn: {
    borderWidth: 1,
    borderColor: "#374151",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  clearAllText: {
    color: "#D1D5DB",
    fontSize: 12,
    fontWeight: "800",
  },
  dropdownDoneBtn: {
    backgroundColor: GREEN,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  dropdownDoneText: {
    color: "#03150A",
    fontSize: 12,
    fontWeight: "900",
  },
  dropdownSearchInput: {
    backgroundColor: "#1A1A1A",
    borderWidth: 1,
    borderColor: "#2A2A2A",
    borderRadius: 10,
    color: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
  },
  allergyBoxList: { maxHeight: 230, paddingHorizontal: 14 },
  boxList: { maxHeight: 230 },
  noResultsText: {
    width: "100%",
    color: "#9CA3AF",
    fontSize: 13,
    paddingVertical: 10,
  },

  oneCol: { flexDirection: "column" },
  twoCols: { flexDirection: "row", flexWrap: "wrap" },
  fullColItem: { width: "100%" },
  colItem: { width: "50%", paddingRight: 8 },

  checkRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    gap: 10,
  },
  checkBox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#4B5563",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  checkBoxOn: { backgroundColor: GREEN, borderColor: GREEN },
  checkMark: { color: "#000", fontWeight: "900", fontSize: 12 },
  checkLabel: { color: "#E5E7EB", fontSize: 13, flex: 1 },
  keyboardWrap: { flex: 1 },
});

export default styles;
