import { StyleSheet } from "react-native";

const GREEN = "#1DB954";

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#000000" },
  container: { flex: 1, backgroundColor: "#000000" },
  scrollView: {
    flex: 1,
    backgroundColor: "#000000",
  },
  header: {
    backgroundColor: "#050505",
    borderBottomWidth: 1,
    borderBottomColor: "#1F2937",
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 18,
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  brandWrap: {
    flexDirection: "row",
    alignItems: "center",
  },
  logo: {
    width: 34,
    height: 34,
    marginRight: 10,
  },
  brandText: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: 0,
  },
  profileBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: GREEN,
    alignItems: "center",
    justifyContent: "center",
  },
  topProfileIconWrap: {
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  topProfileHead: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    borderWidth: 1.6,
    borderColor: "#000000",
    marginBottom: 2,
  },
  topProfileBody: {
    width: 10,
    height: 6,
    borderWidth: 1.6,
    borderTopWidth: 0,
    borderColor: "#000000",
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
  },
  hello: {
    color: "#FFFFFF",
    fontSize: 32,
    fontWeight: "800",
    marginBottom: 8,
  },
  sub: {
    color: "#A3A3A3",
    fontSize: 13,
    lineHeight: 19,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  scanCard: {
    position: "relative",
    overflow: "hidden",
    backgroundColor: GREEN,
    borderRadius: 16,
    padding: 20,
    marginBottom: 14,
  },
  scanRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
  },
  scanIconBox: {
    width: 58,
    height: 58,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  scanFrame: {
    width: 22,
    height: 22,
    position: "relative",
  },
  scanCorner: {
    position: "absolute",
    width: 7,
    height: 7,
    borderColor: "#FFFFFF",
  },
  scanCornerTopLeft: {
    left: 0,
    top: 0,
    borderLeftWidth: 2.2,
    borderTopWidth: 2.2,
    borderTopLeftRadius: 2,
  },
  scanCornerTopRight: {
    right: 0,
    top: 0,
    borderRightWidth: 2.2,
    borderTopWidth: 2.2,
    borderTopRightRadius: 2,
  },
  scanCornerBottomLeft: {
    left: 0,
    bottom: 0,
    borderLeftWidth: 2.2,
    borderBottomWidth: 2.2,
    borderBottomLeftRadius: 2,
  },
  scanCornerBottomRight: {
    right: 0,
    bottom: 0,
    borderRightWidth: 2.2,
    borderBottomWidth: 2.2,
    borderBottomRightRadius: 2,
  },
  scanTextWrap: {
    flex: 1,
  },
  scanTitle: {
    color: "#FFFFFF",
    fontSize: 19,
    fontWeight: "800",
    marginBottom: 4,
  },
  scanSub: {
    color: "#FFFFFF",
    fontSize: 13,
    lineHeight: 18,
    opacity: 0.92,
  },
  scanBtn: {
    backgroundColor: "#E7E7E7",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingVertical: 10,
  },
  scanBtnText: {
    color: "#000000",
    fontWeight: "700",
    fontSize: 15,
  },
  summaryRow: {
    minHeight: 74,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0D0D0D",
    borderWidth: 1,
    borderColor: "#1F2937",
    borderRadius: 14,
    paddingHorizontal: 14,
    marginBottom: 20,
  },
  summaryItem: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  summaryDivider: {
    width: 1,
    height: 36,
    backgroundColor: "#1F2937",
    marginHorizontal: 12,
  },
  summaryValue: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
  },
  summaryLabel: {
    color: "#9CA3AF",
    fontSize: 12,
    marginTop: 2,
  },
  recentHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  recentTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
  },
  moreBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(29,185,84,0.35)",
    backgroundColor: "rgba(29,185,84,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  moreBtnText: {
    color: GREEN,
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 18,
    textAlign: "center",
  },
  scanItem: {
    backgroundColor: "#121212",
    borderWidth: 1,
    borderColor: "#1F2937",
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
  },
  scanItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  scanItemIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "rgba(29,185,84,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  scanItemTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  scanItemTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 4,
  },
  scanItemDate: {
    color: "#A3A3A3",
    fontSize: 13,
  },
  badgesRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  badgeWrap: {
    flexDirection: "row",
    alignItems: "center",
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  dotSafe: {
    backgroundColor: "#22C55E",
  },
  dotWarn: {
    backgroundColor: "#EAB308",
  },
  dotUnsafe: {
    backgroundColor: "#EF4444",
  },
  badgeText: {
    color: "#A3A3A3",
    fontSize: 12,
  },
  safetyCard: {
    marginTop: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(29,185,84,0.35)",
    backgroundColor: "rgba(29,185,84,0.12)",
    padding: 14,
  },
  safetyTitle: {
    color: GREEN,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 6,
  },
  safetyBody: {
    color: "#A3A3A3",
    fontSize: 13,
    lineHeight: 19,
  },
  emptyState: {
    minHeight: 78,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#121212",
    borderWidth: 1,
    borderColor: "#1F2937",
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
  },
  emptyIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "rgba(29,185,84,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTextWrap: {
    flex: 1,
  },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#121212",
    borderTopWidth: 1,
    borderTopColor: "#1F2937",
    paddingHorizontal: 20,
    paddingTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  navLabelActive: {
    color: GREEN,
    fontSize: 11,
    fontWeight: "700",
  },
  navLabel: {
    color: "#9CA3AF",
    fontSize: 11,
  },
  navCenterWrap: {
    marginTop: -18,
  },
  navCenterBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: GREEN,
    alignItems: "center",
    justifyContent: "center",
  },
  uploadIconWrap: {
    width: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  uploadArrowStem: {
    position: "absolute",
    top: 4,
    width: 2.4,
    height: 9,
    backgroundColor: "#000000",
    borderRadius: 2,
  },
  uploadArrowHead: {
    position: "absolute",
    top: 2,
    width: 7,
    height: 7,
    borderTopWidth: 2.2,
    borderLeftWidth: 2.2,
    borderColor: "#000000",
    transform: [{ rotate: "45deg" }],
  },
  uploadTray: {
    position: "absolute",
    bottom: 4,
    width: 14,
    height: 8,
    borderWidth: 2.2,
    borderColor: "#000000",
    borderTopWidth: 0,
    borderRadius: 2,
  },
  iconStrokeActive: {
    borderColor: GREEN,
  },
  iconStrokeInactive: {
    borderColor: "#9CA3AF",
  },
  homeIconWrap: {
    width: 22,
    height: 20,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  homeRoof: {
    position: "absolute",
    top: 1,
    width: 10,
    height: 10,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    transform: [{ rotate: "45deg" }],
    backgroundColor: "transparent",
  },
  homeBody: {
    width: 12,
    height: 10,
    borderWidth: 2,
    borderTopWidth: 0,
    borderRadius: 2,
    backgroundColor: "transparent",
  },
  profileIconWrap: {
    width: 22,
    height: 20,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  profileHead: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    borderWidth: 2,
    borderColor: "#9CA3AF",
    marginBottom: 2,
  },
  profileBody: {
    width: 14,
    height: 8,
    borderWidth: 2,
    borderTopWidth: 0,
    borderColor: "#9CA3AF",
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
});

export default styles;
