import { StyleSheet } from "react-native";

const GREEN = "#1DB954";
const BG = "#000000";
const HEADER = "#000000";
const PANEL = "#111111";
const PANEL_ALT = "#171717";
const BORDER = "rgba(255,255,255,0.12)";
const TEXT = "#FFFFFF";
const TEXT_MUTED = "#A3A3A3";
const TEXT_SOFT = "#D4D4D4";

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: BG,
  },
  container: {
    flex: 1,
    backgroundColor: BG,
  },
  header: {
    backgroundColor: HEADER,
    borderBottomWidth: 1,
    borderBottomColor: "#262626",
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 16,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 130,
  },

  detailHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginTop: 4,
  },
  headerTextWrap: {
    flex: 1,
    paddingRight: 14,
  },
  screenTitle: {
    color: TEXT,
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "900",
    letterSpacing: -0.5,
    marginBottom: 6,
  },
  screenSubtitle: {
    color: TEXT_MUTED,
    fontSize: 14,
    lineHeight: 20,
  },
  highlightText: {
    color: GREEN,
    fontWeight: "900",
  },
  headerIconBox: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: GREEN,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: GREEN,
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },

  searchWrap: {
    position: "relative",
    justifyContent: "center",
  },
  searchIcon: {
    position: "absolute",
    left: 15,
    zIndex: 2,
  },
  searchInput: {
    height: 50,
    backgroundColor: PANEL,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 18,
    color: TEXT,
    paddingLeft: 42,
    paddingRight: 16,
    fontSize: 14,
    fontWeight: "600",
  },

  historyHeroCard: {
    backgroundColor: PANEL,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 30,
    padding: 20,
    marginBottom: 18,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.28,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 6,
  },
  heroBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  heroBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(32,199,101,0.16)",
    borderWidth: 1,
    borderColor: "rgba(32,199,101,0.28)",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  heroBadgeText: {
    color: "#D7FBE8",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1,
    marginLeft: 7,
  },
  heroMiniIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: "center",
    justifyContent: "center",
  },
  historyHeroTitle: {
    color: TEXT,
    fontSize: 25,
    lineHeight: 31,
    fontWeight: "900",
    letterSpacing: -0.3,
    marginBottom: 8,
  },
  historyHeroBody: {
    color: TEXT_MUTED,
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 18,
  },
  historyHeroStats: {
    flexDirection: "row",
  },
  historyHeroStatCard: {
    flex: 1,
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginRight: 10,
  },
  historyHeroStatCardLast: {
    flex: 1,
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 14,
  },
  historyHeroStatValue: {
    color: TEXT,
    fontSize: 21,
    fontWeight: "900",
    marginBottom: 4,
  },
  historyHeroStatLabel: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: "600",
  },

  summaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  summaryCard: {
    width: "48%",
    backgroundColor: PANEL,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 24,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  summaryIconBox: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(32,199,101,0.16)",
    borderWidth: 1,
    borderColor: "rgba(32,199,101,0.28)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  summaryLabel: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 8,
  },
  summaryValue: {
    color: TEXT,
    fontSize: 25,
    fontWeight: "900",
  },
  summaryValueSafe: {
    color: GREEN,
  },
  summaryValueRisky: {
    color: "#F5B400",
  },
  summaryValueUnsafe: {
    color: "#FF4D4D",
  },

  historyCard: {
    backgroundColor: PANEL,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 28,
    padding: 18,
    marginBottom: 14,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.22,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5,
  },
  historyTopAccent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 3,
  },
  historyIntroRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 15,
  },
  historyIntroBody: {
    flex: 1,
  },
  scanIconBox: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
    borderWidth: 1,
  },
  inlineMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  historyDate: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: "600",
  },
  historyCardTitle: {
    color: TEXT,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "900",
    marginBottom: 7,
  },
  historyNarrative: {
    color: TEXT_SOFT,
    fontSize: 14,
    lineHeight: 21,
  },
  historyStatsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 12,
  },
  historyStatPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginRight: 8,
    marginBottom: 8,
  },
  historyStatText: {
    color: "#E5E5E5",
    fontSize: 12,
    fontWeight: "700",
  },
  historyFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  historyFooterText: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: "600",
  },
  openReportButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  openReportText: {
    color: "#E5E5E5",
    fontSize: 12,
    fontWeight: "800",
    marginRight: 8,
  },

  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 7,
  },
  dotSafe: {
    backgroundColor: GREEN,
  },
  dotRisky: {
    backgroundColor: "#F5B400",
  },
  dotUnsafe: {
    backgroundColor: "#FF4D4D",
  },

  accentSafe: {
    backgroundColor: "rgba(32,199,101,0.22)",
    borderColor: "rgba(32,199,101,0.42)",
  },
  accentRisky: {
    backgroundColor: "rgba(245,180,0,0.22)",
    borderColor: "rgba(245,180,0,0.42)",
  },
  accentUnsafe: {
    backgroundColor: "rgba(255,77,77,0.22)",
    borderColor: "rgba(255,77,77,0.42)",
  },
  accentNeutral: {
    backgroundColor: "rgba(163,163,163,0.18)",
    borderColor: "rgba(163,163,163,0.32)",
  },

  badge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  badgeSafe: {
    backgroundColor: "rgba(32,199,101,0.18)",
  },
  badgeWarning: {
    backgroundColor: "rgba(245,180,0,0.18)",
  },
  badgeUnsafe: {
    backgroundColor: "rgba(255,77,77,0.18)",
  },
  badgeNeutral: {
    backgroundColor: "rgba(163,163,163,0.18)",
  },
  badgeTextSafe: {
    color: GREEN,
    fontSize: 12,
    fontWeight: "900",
  },
  badgeTextWarning: {
    color: "#F5B400",
    fontSize: 12,
    fontWeight: "900",
  },
  badgeTextUnsafe: {
    color: "#FF6B6B",
    fontSize: 12,
    fontWeight: "900",
  },
  badgeTextNeutral: {
    color: "#D4D4D4",
    fontSize: 12,
    fontWeight: "900",
  },

  heroCard: {
    backgroundColor: PANEL,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 30,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000000",
    shadowOpacity: 0.22,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  heroTextWrap: {
    flex: 1,
    paddingRight: 14,
  },
  heroEyebrow: {
    color: "#9BE7BA",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  heroTitle: {
    color: TEXT,
    fontSize: 26,
    lineHeight: 32,
    fontWeight: "900",
    letterSpacing: -0.4,
    marginBottom: 8,
  },
  heroBody: {
    color: TEXT_SOFT,
    fontSize: 14,
    lineHeight: 21,
  },
  scoreRing: {
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 4,
    borderColor: GREEN,
    backgroundColor: "rgba(32,199,101,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  scoreValue: {
    color: TEXT,
    fontSize: 22,
    fontWeight: "900",
  },
  scoreLabel: {
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
  },

  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  statCard: {
    flex: 1,
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 10,
    marginRight: 10,
  },
  statCardLast: {
    flex: 1,
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 10,
  },
  statValueSafe: {
    color: GREEN,
    fontSize: 19,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 4,
  },
  statValueRisky: {
    color: "#F5B400",
    fontSize: 19,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 4,
  },
  statValueUnsafe: {
    color: "#FF6B6B",
    fontSize: 19,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 4,
  },
  statLabel: {
    color: TEXT_MUTED,
    fontSize: 12,
    textAlign: "center",
    fontWeight: "700",
  },

  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 16,
  },
  metaChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
    marginRight: 8,
    marginBottom: 8,
  },
  metaChipText: {
    color: "#E5E5E5",
    fontSize: 12,
    fontWeight: "800",
    marginLeft: 6,
  },
  fileLocation: {
    color: TEXT_MUTED,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },

  sectionGroup: {
    marginTop: 8,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  sectionTitle: {
    color: TEXT,
    fontSize: 20,
    fontWeight: "900",
  },
  sectionCount: {
    color: TEXT_MUTED,
    fontSize: 13,
    fontWeight: "700",
  },

  dishCard: {
    borderWidth: 1.4,
    borderRadius: 24,
    padding: 16,
    marginBottom: 14,
    backgroundColor: PANEL,
    overflow: "hidden",
  },
  dishCardSafe: {
    borderColor: "rgba(32,199,101,0.38)",
    backgroundColor: "rgba(8,27,18,0.92)",
  },
  dishCardWarning: {
    borderColor: "rgba(245,180,0,0.42)",
    backgroundColor: "rgba(28,21,7,0.94)",
  },
  dishCardUnsafe: {
    borderColor: "rgba(255,77,77,0.42)",
    backgroundColor: "rgba(29,10,13,0.94)",
  },
  dishCardNeutral: {
    borderColor: "rgba(163,163,163,0.3)",
    backgroundColor: PANEL,
  },
  dishHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 14,
  },
  dishIconBox: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  dishIconBoxSafe: {
    borderColor: "#20C765",
  },
  dishIconBoxRisky: {
    borderColor: "#F5B400",
  },
  dishIconBoxUnsafe: {
    borderColor: "#FF4D4D",
  },
  dishIconBoxNeutral: {
    borderColor: "#A3A3A3",
  },
  dishTitleWrap: {
    flex: 1,
    paddingRight: 10,
  },
  dishEyebrow: {
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.7,
    marginBottom: 4,
  },
  dishTitle: {
    color: TEXT,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "900",
  },
  aiNoteBox: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 16,
    padding: 13,
    marginBottom: 14,
  },
  aiNoteHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  aiNoteLabel: {
    color: TEXT_SOFT,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.7,
    marginLeft: 7,
  },
  aiNoteText: {
    color: "#E5E5E5",
    fontSize: 13,
    lineHeight: 19,
  },
  blockTitle: {
    color: "#E5E5E5",
    fontSize: 13,
    fontWeight: "900",
    marginBottom: 10,
  },
  chipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  ingredientChip: {
    alignSelf: "flex-start",
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
    marginRight: 8,
    marginBottom: 8,
  },
  ingredientChipText: {
    color: "#E5E5E5",
    fontSize: 11,
    fontWeight: "800",
  },

  mutedText: {
    color: TEXT_MUTED,
    fontSize: 13,
    lineHeight: 19,
  },
  statusCard: {
    backgroundColor: PANEL,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 18,
    marginBottom: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  statusText: {
    color: TEXT_SOFT,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
    marginTop: 10,
  },
  errorText: {
    color: "#FCA5A5",
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
    marginTop: 10,
  },

  emptyWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 70,
  },
  emptyIconWrap: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  emptyTitle: {
    color: TEXT,
    fontSize: 19,
    fontWeight: "900",
    marginBottom: 8,
  },
  emptyText: {
    color: TEXT_MUTED,
    textAlign: "center",
    fontSize: 13,
    lineHeight: 19,
    maxWidth: 280,
  },

  paginationWrap: {
    marginTop: 8,
    marginBottom: 12,
  },
  paginationText: {
    color: TEXT_MUTED,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  paginationRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  pageButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PANEL,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 16,
    paddingVertical: 12,
    marginHorizontal: 4,
  },
  pageButtonDisabled: {
    opacity: 0.45,
  },
  pageButtonText: {
    color: TEXT,
    fontSize: 13,
    fontWeight: "800",
    marginHorizontal: 7,
  },

  uploadHeroCard: {
    backgroundColor: PANEL,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 30,
    padding: 20,
    marginBottom: 18,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.28,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 6,
  },
  uploadHeroTitle: {
    color: TEXT,
    fontSize: 25,
    lineHeight: 31,
    fontWeight: "900",
    letterSpacing: -0.3,
    marginBottom: 8,
  },
  uploadHeroBody: {
    color: TEXT_MUTED,
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 18,
  },
  uploadHeroStats: {
    flexDirection: "row",
  },
  uploadHeroStatCard: {
    flex: 1,
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginRight: 10,
  },
  uploadHeroStatCardLast: {
    flex: 1,
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  uploadHeroStatValue: {
    color: TEXT,
    fontSize: 19,
    fontWeight: "900",
    marginBottom: 4,
  },
  uploadHeroStatLabel: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: "700",
  },

  fieldBlock: {
    marginBottom: 20,
  },
  label: {
    color: "#E5E5E5",
    fontSize: 14,
    fontWeight: "900",
    marginBottom: 10,
  },
  input: {
    backgroundColor: PANEL,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 15,
    color: TEXT,
    fontSize: 15,
    fontWeight: "600",
  },
  textarea: {
    minHeight: 160,
    textAlignVertical: "top",
  },
  uploadCard: {
    backgroundColor: PANEL,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 28,
    padding: 22,
    marginBottom: 16,
    overflow: "hidden",
  },
  uploadCardDashed: {
    borderStyle: "dashed",
  },
  uploadCenter: {
    alignItems: "center",
  },
  uploadCardGlow: {
    position: "absolute",
    top: -22,
    right: -14,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(32,199,101,0.08)",
  },
  uploadIconCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  uploadPill: {
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginBottom: 14,
  },
  uploadPillText: {
    color: "#E5E5E5",
    fontSize: 12,
    fontWeight: "800",
  },
  uploadTitle: {
    color: TEXT,
    fontSize: 20,
    fontWeight: "900",
    marginBottom: 6,
  },
  uploadSub: {
    color: TEXT_SOFT,
    fontSize: 14,
    textAlign: "center",
  },
  uploadTiny: {
    color: TEXT_MUTED,
    fontSize: 12,
    textAlign: "center",
    marginTop: 8,
    lineHeight: 17,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: BORDER,
  },
  dividerText: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: "700",
    marginHorizontal: 10,
  },
  actionRowCard: {
    backgroundColor: PANEL,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 22,
    padding: 17,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  actionIconBox: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  actionBody: {
    flex: 1,
  },
  actionTitle: {
    color: "#F3F4F6",
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 4,
  },
  actionSub: {
    color: TEXT_MUTED,
    fontSize: 13,
    fontWeight: "600",
  },
  actionArrowWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: PANEL_ALT,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 12,
  },
  selectedFileCard: {
    backgroundColor: PANEL,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 24,
    padding: 17,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
  },
  selectedFileBody: {
    flex: 1,
  },
  selectedFileName: {
    color: TEXT,
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 4,
  },
  selectedFileMeta: {
    color: TEXT_MUTED,
    fontSize: 13,
    fontWeight: "600",
  },
  selectedFilePill: {
    alignSelf: "flex-start",
    marginTop: 10,
    backgroundColor: "rgba(32,199,101,0.16)",
    borderWidth: 1,
    borderColor: "rgba(32,199,101,0.28)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  selectedFilePillText: {
    color: "#D7FBE8",
    fontSize: 11,
    fontWeight: "900",
  },
  removeFileButton: {
    padding: 6,
  },
  primaryButton: {
    backgroundColor: GREEN,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    marginBottom: 20,
    flexDirection: "row",
    shadowColor: GREEN,
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  primaryButtonDisabled: {
    opacity: 0.5,
  },
  primaryButtonText: {
    color: "#03150A",
    fontSize: 16,
    fontWeight: "900",
    marginLeft: 8,
  },
  infoCard: {
    backgroundColor: PANEL,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 24,
    padding: 16,
  },
  infoTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  infoTitle: {
    color: GREEN,
    fontSize: 15,
    fontWeight: "900",
    marginLeft: 8,
  },
  infoBody: {
    color: TEXT_SOFT,
    fontSize: 13,
    lineHeight: 20,
  },
  infoFeatureRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 12,
  },
  infoFeaturePill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: PANEL_ALT,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginRight: 8,
    marginBottom: 8,
  },
  infoFeatureText: {
    color: "#E5E5E5",
    fontSize: 12,
    fontWeight: "800",
    marginLeft: 6,
  },
  reportWrap: {
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
    marginTop: 8,
    paddingTop: 14,
  },
  reportButton: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  reportButtonText: {
    color: "#E5E5E5",
    fontSize: 12,
    fontWeight: "800",
    marginLeft: 8,
  },
  emptyStateCard: {
    backgroundColor: PANEL,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 24,
    padding: 20,
    marginTop: 8,
    alignItems: "center",
  },
  emptyStateText: {
    color: TEXT_MUTED,
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
  },

  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#0B0B0B",
    borderTopWidth: 1,
    borderTopColor: "#1F2937",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 10,
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 64,
  },
  navLabel: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 5,
  },
  navLabelActive: {
    color: GREEN,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 5,
  },
  navCenterWrap: {
    marginTop: -26,
  },
  navCenterButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: GREEN,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "#0B0B0B",
  },
});

export function getMenuIconBorderStyle(baseStyle, borderColor) {
  return [baseStyle, { borderColor }];
}

export default styles;


