import { StyleSheet } from "react-native";

const GREEN = "#1DB954";

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#000000" },
  container: { flex: 1, backgroundColor: "#000000" },
  header: {
    backgroundColor: "#000000",
    borderBottomWidth: 1,
    borderBottomColor: "#262626",
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 16,
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 22,
  },
  brandWrap: {
    flexDirection: "row",
    alignItems: "center",
  },
  logo: {
    width: 34,
    height: 34,
    marginRight: 10,
  },
  brandText: {
    color: "#FFFFFF",
    fontSize: 30,
    fontWeight: "700",
    letterSpacing: 0.1,
  },
  profileBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: GREEN,
    alignItems: "center",
    justifyContent: "center",
  },
  topProfileIconWrap: {
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  topProfileHead: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    borderWidth: 1.6,
    borderColor: "#000000",
    marginBottom: 2,
  },
  topProfileBody: {
    width: 10,
    height: 6,
    borderWidth: 1.6,
    borderTopWidth: 0,
    borderColor: "#000000",
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
  },
  hello: {
    color: "#FFFFFF",
    fontSize: 36,
    fontWeight: "700",
    marginBottom: 8,
  },
  sub: {
    color: "#C4C4C4",
    fontSize: 13,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 22,
    paddingBottom: 120,
  },
  scanCard: {
    backgroundColor: GREEN,
    borderRadius: 14,
    padding: 22,
    marginBottom: 20,
  },
  scanRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 22,
  },
  scanIconBox: {
    width: 60,
    height: 60,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  scanFrame: {
    width: 22,
    height: 22,
    position: "relative",
  },
  scanCorner: {
    position: "absolute",
    width: 7,
    height: 7,
    borderColor: "#FFFFFF",
  },
  scanCornerTopLeft: {
    left: 0,
    top: 0,
    borderLeftWidth: 2.2,
    borderTopWidth: 2.2,
    borderTopLeftRadius: 2,
  },
  scanCornerTopRight: {
    right: 0,
    top: 0,
    borderRightWidth: 2.2,
    borderTopWidth: 2.2,
    borderTopRightRadius: 2,
  },
  scanCornerBottomLeft: {
    left: 0,
    bottom: 0,
    borderLeftWidth: 2.2,
    borderBottomWidth: 2.2,
    borderBottomLeftRadius: 2,
  },
  scanCornerBottomRight: {
    right: 0,
    bottom: 0,
    borderRightWidth: 2.2,
    borderBottomWidth: 2.2,
    borderBottomRightRadius: 2,
  },
  scanTextWrap: {
    flex: 1,
  },
  scanTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 4,
  },
  scanSub: {
    color: "#FFFFFF",
    fontSize: 13,
  },
  scanBtn: {
    backgroundColor: "#E7E7E7",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  scanBtnText: {
    color: "#000000",
    fontWeight: "700",
    fontSize: 15,
  },
  recentHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  recentTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
  },
  moreBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(29,185,84,0.35)",
    backgroundColor: "rgba(29,185,84,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  moreBtnText: {
    color: GREEN,
    fontSize: 18,
    fontWeight: "700",
    marginTop: -4,
  },
  scanItem: {
    backgroundColor: "#121212",
    borderWidth: 1,
    borderColor: "#262626",
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
  },
  scanItemTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 4,
  },
  scanItemDate: {
    color: "#A3A3A3",
    fontSize: 13,
    marginBottom: 10,
  },
  badgesRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  badgeWrap: {
    flexDirection: "row",
    alignItems: "center",
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  dotSafe: {
    backgroundColor: "#22C55E",
  },
  dotWarn: {
    backgroundColor: "#EAB308",
  },
  dotUnsafe: {
    backgroundColor: "#EF4444",
  },
  badgeText: {
    color: "#A3A3A3",
    fontSize: 12,
  },
  safetyCard: {
    marginTop: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(29,185,84,0.35)",
    backgroundColor: "rgba(29,185,84,0.12)",
    padding: 14,
  },
  safetyTitle: {
    color: GREEN,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 6,
  },
  safetyBody: {
    color: "#A3A3A3",
    fontSize: 13,
    lineHeight: 19,
  },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#0B0B0B",
    borderTopWidth: 1,
    borderTopColor: "#1F2937",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 10,
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 64,
  },
  navLabelActive: {
    color: GREEN,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 5,
  },
  navLabel: {
    color: "#9CA3AF",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 5,
  },
  navCenterWrap: {
    marginTop: -26,
  },
  navCenterBtn: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: GREEN,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "#0B0B0B",
  },
  uploadIconWrap: {
    width: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  uploadArrowStem: {
    position: "absolute",
    top: 4,
    width: 2.4,
    height: 9,
    backgroundColor: "#000000",
    borderRadius: 2,
  },
  uploadArrowHead: {
    position: "absolute",
    top: 2,
    width: 7,
    height: 7,
    borderTopWidth: 2.2,
    borderLeftWidth: 2.2,
    borderColor: "#000000",
    transform: [{ rotate: "45deg" }],
  },
  uploadTray: {
    position: "absolute",
    bottom: 4,
    width: 14,
    height: 8,
    borderWidth: 2.2,
    borderColor: "#000000",
    borderTopWidth: 0,
    borderRadius: 2,
  },
  iconStrokeActive: {
    borderColor: GREEN,
  },
  iconStrokeInactive: {
    borderColor: "#9CA3AF",
  },
  homeIconWrap: {
    width: 22,
    height: 20,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  homeRoof: {
    position: "absolute",
    top: 1,
    width: 10,
    height: 10,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    transform: [{ rotate: "45deg" }],
    backgroundColor: "transparent",
  },
  homeBody: {
    width: 12,
    height: 10,
    borderWidth: 2,
    borderTopWidth: 0,
    borderRadius: 2,
    backgroundColor: "transparent",
  },
  profileIconWrap: {
    width: 22,
    height: 20,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  profileHead: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    borderWidth: 2,
    borderColor: "#9CA3AF",
    marginBottom: 2,
  },
  profileBody: {
    width: 14,
    height: 8,
    borderWidth: 2,
    borderTopWidth: 0,
    borderColor: "#9CA3AF",
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
});

export default styles;
